import { StyleSheet } from 'react-native';

export const verificationStyles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 2.0)',
    zIndex: 0,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 1,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 25,
    width: '90%',
    maxWidth: 350,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  iconContainer: {
    marginBottom: 15,
  },
  icon: {
    width: 60,
    height: 60,
    tintColor: '#2E3A59',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2E3A59',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#fff',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
    opacity: 1.0,
  },
  emailText: {
    fontSize: 13,
    color: '#fff',
    marginBottom: 25,
    textAlign: 'center',
    fontStyle: 'italic',
    opacity: 1.0,
  },
  codeInput: {
    width: '70%',
    height: 50,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    fontSize: 20,
    fontWeight: '600',
    color: '#2E3A59',
    textAlign: 'center',
    marginBottom: 25,
    backgroundColor: '#fafafa',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  verifyButton: {
    backgroundColor: '#2E3A59',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginBottom: 15,
    width: '80%',
    alignItems: 'center',
  },
  verifyButtonDisabled: {
    backgroundColor: '#7A8BA3',
    opacity: 0.7,
  },
  verifyButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '600',
  },
  backButton: {
    paddingVertical: 8,
  },
  backButtonText: {
    color: '#666',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
});