import { StyleSheet } from 'react-native';

export const verificationStyles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    zIndex: 0,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 1,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 25,
    padding: 35,
    width: '90%',
    maxWidth: 380,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(46, 58, 89, 0.1)',
  },
  iconContainer: {
    marginBottom: 20,
    backgroundColor: 'rgba(46, 58, 89, 0.1)',
    borderRadius: 50,
    padding: 15,
  },
  icon: {
    width: 50,
    height: 50,
    tintColor: '#2E3A59',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2E3A59',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
    paddingHorizontal: 10,
  },
  emailText: {
    fontSize: 14,
    color: '#2E3A59',
    marginBottom: 30,
    textAlign: 'center',
    fontWeight: '500',
    backgroundColor: 'rgba(46, 58, 89, 0.05)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(46, 58, 89, 0.1)',
  },
  codeInput: {
    width: '85%',
    height: 65,
    borderWidth: 2,
    borderColor: '#2E3A59',
    borderRadius: 15,
    fontSize: 26,
    fontWeight: '700',
    color: '#2E3A59',
    textAlign: 'center',
    marginBottom: 30,
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 20,
    letterSpacing: 10,
    shadowColor: '#2E3A59',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  verifyButton: {
    backgroundColor: '#2E3A59',
    paddingVertical: 16,
    paddingHorizontal: 45,
    borderRadius: 15,
    marginBottom: 20,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#2E3A59',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  verifyButtonDisabled: {
    backgroundColor: '#7A8BA3',
    shadowOpacity: 0.1,
    elevation: 1,
  },
  verifyButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  backButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  backButtonText: {
    color: '#2E3A59',
    fontSize: 14,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  instructionText: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginBottom: 10,
    fontStyle: 'italic',
  },
});