import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
    zIndex: 0,
  },
  container: {
    flexGrow: 1,
    zIndex: 1,
  },
  header: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 2,
  },
  backIcon: {
    width: 28,
    height: 28,
    tintColor: '#fff',
  },
  mainContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 50,
  },
  logoContainer: {
    marginBottom: 30,
  },
  logoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  logo: {
    width: 60,
    height: 60,
  },
  titleContainer: {
    marginBottom: 40,
  },
  loginTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
  },
  formContainer: {
    width: '100%',
    maxWidth: 320,
    gap: 15,
    // Evita que el teclado empuje el formulario bruscamente
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 52,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 2,
  },
  inputIcon: {
    width: 25,
    height: 35,
    marginRight: 12,
    tintColor: '#666',
    resizeMode: 'contain',
  },
  eyeIcon: {
    width: 28,
    height: 28,
    marginLeft: 12,
    tintColor: '#666',
    resizeMode: 'contain',
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    paddingVertical: 0,
    textAlignVertical: 'center', // Centra el texto verticalmente y evita saltos
  },
  loginButton: {
    backgroundColor: '#2E3A59',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  loginButtonDisabled: {
    backgroundColor: '#7A8BA3',
    opacity: 0.7,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  switchButton: {
    marginTop: 20,
    paddingVertical: 12,
    alignItems: 'center',
  },
  switchButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  picker: {
    flex: 1,
    color: '#333',
    fontSize: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#fff',
    textAlign: 'center',
    marginBottom: 25,
    opacity: 0.9,
    lineHeight: 22,
  },
  emailText: {
    fontSize: 14,
    color: '#fff',
    textAlign: 'center',
    marginBottom: 15,
    opacity: 0.8,
    fontStyle: 'italic',
  },
  verificationLogo: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  verificationInput: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 4,
    color: '#2E3A59',
    textAlign: 'center',
  },
  instructionText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '500',
  },
});
